export const SessionState = Object.freeze({
  IDLE: 'IDLE',
  SYNCING: 'SYNCING',
  OPENING: 'OPENING',
  COLLECTING_ACTIONS: 'COLLECTING_ACTIONS',
  RESOLVING: 'RESOLVING',
  NARRATING: 'NARRATING',
  PAUSED: 'PAUSED',
  ENDED: 'ENDED'
});
